# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Qgs18/apps/qgis/python/plugins/TopoDelProp/forms_ui/frmPpal.ui'
#
# Created: Fri Nov 09 12:36:58 2012
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmPpal(object):
    def setupUi(self, frmPpal):
        frmPpal.setObjectName(_fromUtf8("frmPpal"))
        frmPpal.setWindowModality(QtCore.Qt.NonModal)
        frmPpal.resize(221, 477)
        frmPpal.setWindowTitle(QtGui.QApplication.translate("frmPpal", "TopoDelProp", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(frmPpal)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.treeView = QtGui.QTreeView(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(0, 0, 221, 401))
        self.treeView.setAllColumnsShowFocus(False)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.txtInfo = QtGui.QLineEdit(self.centralwidget)
        self.txtInfo.setGeometry(QtCore.QRect(0, 400, 221, 22))
        self.txtInfo.setText(_fromUtf8(""))
        self.txtInfo.setObjectName(_fromUtf8("txtInfo"))
        frmPpal.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(frmPpal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 221, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setTitle(QtGui.QApplication.translate("frmPpal", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menuUsuOperacionesFincas = QtGui.QMenu(self.menu)
        self.menuUsuOperacionesFincas.setTitle(QtGui.QApplication.translate("frmPpal", "Operaciones con fincas", None, QtGui.QApplication.UnicodeUTF8))
        self.menuUsuOperacionesFincas.setObjectName(_fromUtf8("menuUsuOperacionesFincas"))
        self.menuConsultar_trabajo = QtGui.QMenu(self.menu)
        self.menuConsultar_trabajo.setTitle(QtGui.QApplication.translate("frmPpal", "Consultar-editar trabajo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConsultar_trabajo.setObjectName(_fromUtf8("menuConsultar_trabajo"))
        self.menuBuscar_por_referencia_catastral = QtGui.QMenu(self.menuConsultar_trabajo)
        self.menuBuscar_por_referencia_catastral.setTitle(QtGui.QApplication.translate("frmPpal", "Buscar por referencia catastral", None, QtGui.QApplication.UnicodeUTF8))
        self.menuBuscar_por_referencia_catastral.setObjectName(_fromUtf8("menuBuscar_por_referencia_catastral"))
        self.menuComprobar_finca = QtGui.QMenu(self.menu)
        self.menuComprobar_finca.setTitle(QtGui.QApplication.translate("frmPpal", "Comprobar finca", None, QtGui.QApplication.UnicodeUTF8))
        self.menuComprobar_finca.setObjectName(_fromUtf8("menuComprobar_finca"))
        self.menuAyuda = QtGui.QMenu(self.menubar)
        self.menuAyuda.setTitle(QtGui.QApplication.translate("frmPpal", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAyuda.setObjectName(_fromUtf8("menuAyuda"))
        frmPpal.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(frmPpal)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        frmPpal.setStatusBar(self.statusbar)
        self.opNuevoTrabajo = QtGui.QAction(frmPpal)
        self.opNuevoTrabajo.setText(QtGui.QApplication.translate("frmPpal", "Nuevo trabajo", None, QtGui.QApplication.UnicodeUTF8))
        self.opNuevoTrabajo.setToolTip(QtGui.QApplication.translate("frmPpal", "Crea un nuevo trabajo", None, QtGui.QApplication.UnicodeUTF8))
        self.opNuevoTrabajo.setObjectName(_fromUtf8("opNuevoTrabajo"))
        self.opUsuEditarTrabajo = QtGui.QAction(frmPpal)
        self.opUsuEditarTrabajo.setText(QtGui.QApplication.translate("frmPpal", "Editar trabajo", None, QtGui.QApplication.UnicodeUTF8))
        self.opUsuEditarTrabajo.setToolTip(QtGui.QApplication.translate("frmPpal", "Editar trabajo existente", None, QtGui.QApplication.UnicodeUTF8))
        self.opUsuEditarTrabajo.setObjectName(_fromUtf8("opUsuEditarTrabajo"))
        self.actionOo3 = QtGui.QAction(frmPpal)
        self.actionOo3.setText(QtGui.QApplication.translate("frmPpal", "oo3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOo3.setObjectName(_fromUtf8("actionOo3"))
        self.actionOo4 = QtGui.QAction(frmPpal)
        self.actionOo4.setText(QtGui.QApplication.translate("frmPpal", "oo4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOo4.setObjectName(_fromUtf8("actionOo4"))
        self.opVerHistorico = QtGui.QAction(frmPpal)
        self.opVerHistorico.setText(QtGui.QApplication.translate("frmPpal", "Ver historico de una finca", None, QtGui.QApplication.UnicodeUTF8))
        self.opVerHistorico.setObjectName(_fromUtf8("opVerHistorico"))
        self.opAgreDivVert = QtGui.QAction(frmPpal)
        self.opAgreDivVert.setText(QtGui.QApplication.translate("frmPpal", "Agregar division vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.opAgreDivVert.setObjectName(_fromUtf8("opAgreDivVert"))
        self.opDividirFinca = QtGui.QAction(frmPpal)
        self.opDividirFinca.setText(QtGui.QApplication.translate("frmPpal", "Dividir finca", None, QtGui.QApplication.UnicodeUTF8))
        self.opDividirFinca.setObjectName(_fromUtf8("opDividirFinca"))
        self.opAgregarFinca = QtGui.QAction(frmPpal)
        self.opAgregarFinca.setText(QtGui.QApplication.translate("frmPpal", "Agregar finca", None, QtGui.QApplication.UnicodeUTF8))
        self.opAgregarFinca.setObjectName(_fromUtf8("opAgregarFinca"))
        self.opSegregarFinca = QtGui.QAction(frmPpal)
        self.opSegregarFinca.setText(QtGui.QApplication.translate("frmPpal", "Segregar finca", None, QtGui.QApplication.UnicodeUTF8))
        self.opSegregarFinca.setObjectName(_fromUtf8("opSegregarFinca"))
        self.opUsuBuscarTrabajo = QtGui.QAction(frmPpal)
        self.opUsuBuscarTrabajo.setText(QtGui.QApplication.translate("frmPpal", "Buscar por datos del trabajo", None, QtGui.QApplication.UnicodeUTF8))
        self.opUsuBuscarTrabajo.setObjectName(_fromUtf8("opUsuBuscarTrabajo"))
        self.actionBuscar_por_datos_de_la_finca = QtGui.QAction(frmPpal)
        self.actionBuscar_por_datos_de_la_finca.setText(QtGui.QApplication.translate("frmPpal", "Buscar por datos de la finca", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuscar_por_datos_de_la_finca.setObjectName(_fromUtf8("actionBuscar_por_datos_de_la_finca"))
        self.actionBuscar_por_referencia_catastral = QtGui.QAction(frmPpal)
        self.actionBuscar_por_referencia_catastral.setText(QtGui.QApplication.translate("frmPpal", "Buscar por referencia catastral", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuscar_por_referencia_catastral.setObjectName(_fromUtf8("actionBuscar_por_referencia_catastral"))
        self.actionBuscar_por_propietario = QtGui.QAction(frmPpal)
        self.actionBuscar_por_propietario.setText(QtGui.QApplication.translate("frmPpal", "Buscar por propietario", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuscar_por_propietario.setObjectName(_fromUtf8("actionBuscar_por_propietario"))
        self.actionBuscar_por_cliente = QtGui.QAction(frmPpal)
        self.actionBuscar_por_cliente.setText(QtGui.QApplication.translate("frmPpal", "Buscar por cliente", None, QtGui.QApplication.UnicodeUTF8))
        self.actionBuscar_por_cliente.setObjectName(_fromUtf8("actionBuscar_por_cliente"))
        self.opAcercaDe = QtGui.QAction(frmPpal)
        self.opAcercaDe.setText(QtGui.QApplication.translate("frmPpal", "Acerca de ...", None, QtGui.QApplication.UnicodeUTF8))
        self.opAcercaDe.setObjectName(_fromUtf8("opAcercaDe"))
        self.opAyuda = QtGui.QAction(frmPpal)
        self.opAyuda.setText(QtGui.QApplication.translate("frmPpal", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.opAyuda.setObjectName(_fromUtf8("opAyuda"))
        self.opAdminBuscarPorTrabajo = QtGui.QAction(frmPpal)
        self.opAdminBuscarPorTrabajo.setText(QtGui.QApplication.translate("frmPpal", "Buscar por datos del trabajo", None, QtGui.QApplication.UnicodeUTF8))
        self.opAdminBuscarPorTrabajo.setObjectName(_fromUtf8("opAdminBuscarPorTrabajo"))
        self.opAdminBuscarPorFinca = QtGui.QAction(frmPpal)
        self.opAdminBuscarPorFinca.setText(QtGui.QApplication.translate("frmPpal", "Buscar por datos de la finca", None, QtGui.QApplication.UnicodeUTF8))
        self.opAdminBuscarPorFinca.setObjectName(_fromUtf8("opAdminBuscarPorFinca"))
        self.opAdminBuscarporRefCat = QtGui.QAction(frmPpal)
        self.opAdminBuscarporRefCat.setText(QtGui.QApplication.translate("frmPpal", "Buscar por referencia catastral", None, QtGui.QApplication.UnicodeUTF8))
        self.opAdminBuscarporRefCat.setObjectName(_fromUtf8("opAdminBuscarporRefCat"))
        self.opAdminBuscarPorPropiet = QtGui.QAction(frmPpal)
        self.opAdminBuscarPorPropiet.setText(QtGui.QApplication.translate("frmPpal", "Buscar por propietario", None, QtGui.QApplication.UnicodeUTF8))
        self.opAdminBuscarPorPropiet.setObjectName(_fromUtf8("opAdminBuscarPorPropiet"))
        self.opAdminBuscarPorCliente = QtGui.QAction(frmPpal)
        self.opAdminBuscarPorCliente.setText(QtGui.QApplication.translate("frmPpal", "Buscar por cliente", None, QtGui.QApplication.UnicodeUTF8))
        self.opAdminBuscarPorCliente.setObjectName(_fromUtf8("opAdminBuscarPorCliente"))
        self.actionValidar_trabajo = QtGui.QAction(frmPpal)
        self.actionValidar_trabajo.setText(QtGui.QApplication.translate("frmPpal", "Validar trabajo", None, QtGui.QApplication.UnicodeUTF8))
        self.actionValidar_trabajo.setObjectName(_fromUtf8("actionValidar_trabajo"))
        self.opBuscarPorTrabajo = QtGui.QAction(frmPpal)
        self.opBuscarPorTrabajo.setText(QtGui.QApplication.translate("frmPpal", "Buscar por datos del trabajo", None, QtGui.QApplication.UnicodeUTF8))
        self.opBuscarPorTrabajo.setObjectName(_fromUtf8("opBuscarPorTrabajo"))
        self.opBuscarPorFinca = QtGui.QAction(frmPpal)
        self.opBuscarPorFinca.setText(QtGui.QApplication.translate("frmPpal", "Buscar por datos de la finca", None, QtGui.QApplication.UnicodeUTF8))
        self.opBuscarPorFinca.setObjectName(_fromUtf8("opBuscarPorFinca"))
        self.opValidarTrabajo = QtGui.QAction(frmPpal)
        self.opValidarTrabajo.setText(QtGui.QApplication.translate("frmPpal", "Validar trabajo", None, QtGui.QApplication.UnicodeUTF8))
        self.opValidarTrabajo.setObjectName(_fromUtf8("opValidarTrabajo"))
        self.opBuscarPorPropietarios = QtGui.QAction(frmPpal)
        self.opBuscarPorPropietarios.setText(QtGui.QApplication.translate("frmPpal", "Buscar por propietarios", None, QtGui.QApplication.UnicodeUTF8))
        self.opBuscarPorPropietarios.setObjectName(_fromUtf8("opBuscarPorPropietarios"))
        self.opBuscarPorClientes = QtGui.QAction(frmPpal)
        self.opBuscarPorClientes.setText(QtGui.QApplication.translate("frmPpal", "Buscar por clientes", None, QtGui.QApplication.UnicodeUTF8))
        self.opBuscarPorClientes.setObjectName(_fromUtf8("opBuscarPorClientes"))
        self.opBuscarPorColindantes = QtGui.QAction(frmPpal)
        self.opBuscarPorColindantes.setText(QtGui.QApplication.translate("frmPpal", "Buscar por colindantes", None, QtGui.QApplication.UnicodeUTF8))
        self.opBuscarPorColindantes.setObjectName(_fromUtf8("opBuscarPorColindantes"))
        self.opBuscarPorRefCatRus = QtGui.QAction(frmPpal)
        self.opBuscarPorRefCatRus.setText(QtGui.QApplication.translate("frmPpal", "Rústica", None, QtGui.QApplication.UnicodeUTF8))
        self.opBuscarPorRefCatRus.setObjectName(_fromUtf8("opBuscarPorRefCatRus"))
        self.opBuscarPorRefCatUrb = QtGui.QAction(frmPpal)
        self.opBuscarPorRefCatUrb.setText(QtGui.QApplication.translate("frmPpal", "Urbana", None, QtGui.QApplication.UnicodeUTF8))
        self.opBuscarPorRefCatUrb.setObjectName(_fromUtf8("opBuscarPorRefCatUrb"))
        self.opRecargarTrabajo = QtGui.QAction(frmPpal)
        self.opRecargarTrabajo.setText(QtGui.QApplication.translate("frmPpal", "Recargar trabajo actual", None, QtGui.QApplication.UnicodeUTF8))
        self.opRecargarTrabajo.setObjectName(_fromUtf8("opRecargarTrabajo"))
        self.opBorrarTrabajo = QtGui.QAction(frmPpal)
        self.opBorrarTrabajo.setText(QtGui.QApplication.translate("frmPpal", "Borrar trabajo", None, QtGui.QApplication.UnicodeUTF8))
        self.opBorrarTrabajo.setObjectName(_fromUtf8("opBorrarTrabajo"))
        self.opCrearUsuarios = QtGui.QAction(frmPpal)
        self.opCrearUsuarios.setText(QtGui.QApplication.translate("frmPpal", "Crear usuarios", None, QtGui.QApplication.UnicodeUTF8))
        self.opCrearUsuarios.setObjectName(_fromUtf8("opCrearUsuarios"))
        self.opCreaUsuarios = QtGui.QAction(frmPpal)
        self.opCreaUsuarios.setText(QtGui.QApplication.translate("frmPpal", "Crear usuarios", None, QtGui.QApplication.UnicodeUTF8))
        self.opCreaUsuarios.setObjectName(_fromUtf8("opCreaUsuarios"))
        self.opBuscaUsuarios = QtGui.QAction(frmPpal)
        self.opBuscaUsuarios.setText(QtGui.QApplication.translate("frmPpal", "Buscar usuarios", None, QtGui.QApplication.UnicodeUTF8))
        self.opBuscaUsuarios.setObjectName(_fromUtf8("opBuscaUsuarios"))
        self.opCargarCapasErrores = QtGui.QAction(frmPpal)
        self.opCargarCapasErrores.setText(QtGui.QApplication.translate("frmPpal", "Cargar capas de solapes y huecos", None, QtGui.QApplication.UnicodeUTF8))
        self.opCargarCapasErrores.setObjectName(_fromUtf8("opCargarCapasErrores"))
        self.opComprobarErroresFinca = QtGui.QAction(frmPpal)
        self.opComprobarErroresFinca.setText(QtGui.QApplication.translate("frmPpal", "Comprobar solapes y huecos", None, QtGui.QApplication.UnicodeUTF8))
        self.opComprobarErroresFinca.setObjectName(_fromUtf8("opComprobarErroresFinca"))
        self.opBorrarErroresFinca = QtGui.QAction(frmPpal)
        self.opBorrarErroresFinca.setText(QtGui.QApplication.translate("frmPpal", "Borrar solapes y huecos de este trabajo", None, QtGui.QApplication.UnicodeUTF8))
        self.opBorrarErroresFinca.setObjectName(_fromUtf8("opBorrarErroresFinca"))
        self.opBorrarErroresSRC = QtGui.QAction(frmPpal)
        self.opBorrarErroresSRC.setText(QtGui.QApplication.translate("frmPpal", "Borrar solapes y huecos de los trabajos del SRC", None, QtGui.QApplication.UnicodeUTF8))
        self.opBorrarErroresSRC.setObjectName(_fromUtf8("opBorrarErroresSRC"))
        self.menuUsuOperacionesFincas.addAction(self.opAgreDivVert)
        self.menuUsuOperacionesFincas.addAction(self.opDividirFinca)
        self.menuUsuOperacionesFincas.addAction(self.opAgregarFinca)
        self.menuUsuOperacionesFincas.addAction(self.opSegregarFinca)
        self.menuBuscar_por_referencia_catastral.addAction(self.opBuscarPorRefCatRus)
        self.menuBuscar_por_referencia_catastral.addAction(self.opBuscarPorRefCatUrb)
        self.menuConsultar_trabajo.addAction(self.opRecargarTrabajo)
        self.menuConsultar_trabajo.addAction(self.opBuscarPorTrabajo)
        self.menuConsultar_trabajo.addAction(self.opBuscarPorFinca)
        self.menuConsultar_trabajo.addAction(self.menuBuscar_por_referencia_catastral.menuAction())
        self.menuConsultar_trabajo.addAction(self.opBuscarPorPropietarios)
        self.menuConsultar_trabajo.addAction(self.opBuscarPorClientes)
        self.menuConsultar_trabajo.addAction(self.opBuscarPorColindantes)
        self.menuComprobar_finca.addAction(self.opCargarCapasErrores)
        self.menuComprobar_finca.addAction(self.opComprobarErroresFinca)
        self.menuComprobar_finca.addAction(self.opBorrarErroresFinca)
        self.menuComprobar_finca.addAction(self.opBorrarErroresSRC)
        self.menu.addAction(self.opNuevoTrabajo)
        self.menu.addAction(self.menuUsuOperacionesFincas.menuAction())
        self.menu.addAction(self.menuComprobar_finca.menuAction())
        self.menu.addAction(self.opBorrarTrabajo)
        self.menu.addAction(self.opValidarTrabajo)
        self.menu.addSeparator()
        self.menu.addAction(self.menuConsultar_trabajo.menuAction())
        self.menu.addAction(self.opVerHistorico)
        self.menuAyuda.addAction(self.opAyuda)
        self.menuAyuda.addAction(self.opAcercaDe)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(frmPpal)
        QtCore.QMetaObject.connectSlotsByName(frmPpal)

    def retranslateUi(self, frmPpal):
        pass


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    frmPpal = QtGui.QMainWindow()
    ui = Ui_frmPpal()
    ui.setupUi(frmPpal)
    frmPpal.show()
    sys.exit(app.exec_())

